server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: hello
    url: jdbc:mysql://localhost:3306/pter?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
  data:
    redis:
      database: 1
      timeout: 600ms
  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: 300000
  messages:
    basename: i18n/messages
mybatis:
  configuration:
    map-underscore-to-camel-case: true

user:
  password:
    maxRetryCount: 3
    lockTime: 10
# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30
  # 是否限制多端登录
  soloLogin: true
pter:
  captchaType: math

retrofit:
  global-converter-factories:
    - com.github.lianjiatech.retrofit.spring.boot.core.BasicTypeConverterFactory
    - retrofit2.converter.jackson.JacksonConverterFactory
  global-log:
    enable: true
    log-level: info
    log-strategy: basic
  global-retry:
    enable: false
    interval-ms: 100 #重试间隔
    max-retries: 2 # 最大重试次数
    retry-rules:
      - response_status_not_2xx
      - occur_io_exception
  global-timeout:
    read-timeout-ms: 10000  # 全局读取超时配置
    write-timeout-ms: 10000  # 全局写入超时配置
    connect-timeout-ms: 10000  # 全局链接超时时间
    call-timeout-ms: 0  # 全局完整调用超时时间
  auto-set-prototype-scope-for-path-math-interceptor: true  # 自动设置PathMathInterceptor的scope为prototype